server:
  port: 8484

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: deposito-service
          uri: http://localhost:8181
          predicates:
            - Path=/deposito/**
        - id: giro-service
          uri: http://localhost:8282
          predicates:
            - Path=/giro/**
        - id: resumen-service
          uri: http://localhost:8383
          predicates:
            - Path=/resumen/**
        